apiVersion: v1
kind: Service
metadata:
  labels:
    name: world-service
  name: world-service
#  annotations:
#    kubernetes.io/ingress.global-static-ip-name: "ip-address"
spec:
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8080
  selector:
    name: world-node
  type: LoadBalancer  
  loadBalancerIP: 34.85.105.34